version: '3'
services:

  database:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: p_afterclassroom
      POSTGRES_USER: u_afterclassroom
      POSTGRES_DB: d_afterclassroom
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5430:5432'

  server:
    container_name: web
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html/
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - 8000:80
    depends_on:
      - "database"